import type { ContentType } from "./types"

const contentData: ContentType[] =[
  {
    "id": "1",
    "title": "Cosmic Odyssey",
    "description": "A team of astronauts embarks on a perilous journey to save humanity from extinction by finding a new habitable planet in a distant galaxy.",
    "thumbnail": "https://picsum.photos/200/120?random=1",
    "coverImage": "https://picsum.photos/1600/800?random=1",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "releaseYear": 2023,
    "duration": "2h 45m",
    "rating": "PG-13",
    "genres": ["Sci-Fi", "Adventure", "Drama"],
    "cast": ["Emma Stone", "Ryan Gosling", "Idris Elba", "Zoe Saldana"],
    "matchPercentage": 98,
    "isTrending": true,
    "isNewRelease": true
  },
  {
    "id": "2",
    "title": "The Last Kingdom",
    "description": "In a medieval world torn by war, a young warrior must navigate political intrigue and battlefield chaos to reclaim his ancestral lands.",
    "thumbnail": "https://picsum.photos/200/120?random=2",
    "coverImage": "https://picsum.photos/1600/800?random=2",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "releaseYear": 2022,
    "duration": "2h 15m",
    "rating": "R",
    "genres": ["Action", "History", "Drama"],
    "cast": ["Henry Cavill", "Anya Taylor-Joy", "Oscar Isaac", "Florence Pugh"],
    "matchPercentage": 95,
    "isTrending": true,
    "isNewRelease": false
  },
  {
    "id": "3",
    "title": "Neon Shadows",
    "description": "In a dystopian future where corporations rule, a hacker uncovers a conspiracy that could either save humanity or plunge it further into darkness.",
    "thumbnail": "https://picsum.photos/200/120?random=3",
    "coverImage": "https://picsum.photos/1600/800?random=3",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "releaseYear": 2023,
    "duration": "2h 10m",
    "rating": "R",
    "genres": ["Sci-Fi", "Thriller", "Action"],
    "cast": ["Keanu Reeves", "Ana de Armas", "John Boyega", "Karen Gillan"],
    "matchPercentage": 92,
    "isTrending": true,
    "isNewRelease": true
  },
  {
    "id": "4",
    "title": "Eternal Eclipse",
    "description": "A group of survivors on a space station must deal with a new cosmic threat that could spell the end of their civilization.",
    "thumbnail": "https://picsum.photos/200/120?random=4",
    "coverImage": "https://picsum.photos/1600/800?random=4",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    "releaseYear": 2024,
    "duration": "2h 30m",
    "rating": "PG-13",
    "genres": ["Sci-Fi", "Thriller"],
    "cast": ["Jessica Chastain", "Matt Damon", "Chris Hemsworth"],
    "matchPercentage": 91,
    "isTrending": false,
    "isNewRelease": true
  },
  {
    "id": "5",
    "title": "Horizon Beyond",
    "description": "Exploring the final frontier, a space expedition faces unexpected challenges as they try to chart a new galaxy.",
    "thumbnail": "https://picsum.photos/200/120?random=5",
    "coverImage": "https://picsum.photos/1600/800?random=5",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "releaseYear": 2024,
    "duration": "2h 20m",
    "rating": "PG",
    "genres": ["Sci-Fi", "Adventure"],
    "cast": ["Matthew McConaughey", "Charlize Theron", "Harrison Ford"],
    "matchPercentage": 89,
    "isTrending": false,
    "isNewRelease": true
  },
  {
    "id": "6",
    "title": "The Phantom Horizon",
    "description": "A military captain leads a covert mission to uncover the mysteries behind a mysterious space anomaly.",
    "thumbnail": "https://picsum.photos/200/120?random=6",
    "coverImage": "https://picsum.photos/1600/800?random=6",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    "releaseYear": 2023,
    "duration": "2h 15m",
    "rating": "R",
    "genres": ["Action", "Sci-Fi", "Mystery"],
    "cast": ["Tom Hardy", "Scarlett Johansson", "Morgan Freeman"],
    "matchPercentage": 87,
    "isTrending": true,
    "isNewRelease": false
  },
  {
    "id": "7",
    "title": "Reckless Justice",
    "description": "A seasoned detective is drawn into a web of crime and corruption, seeking justice while uncovering buried secrets.",
    "thumbnail": "https://picsum.photos/200/120?random=7",
    "coverImage": "https://picsum.photos/1600/800?random=7",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "releaseYear": 2023,
    "duration": "2h 10m",
    "rating": "R",
    "genres": ["Crime", "Thriller", "Drama"],
    "cast": ["Ryan Reynolds", "Rachel McAdams", "Samuel L. Jackson"],
    "matchPercentage": 85,
    "isTrending": false,
    "isNewRelease": true
  },
  {
    "id": "8",
    "title": "Kingdoms of Steel",
    "description": "In a world of steel and blood, a warrior fights to unite warring factions against an ancient evil awakening beneath the earth.",
    "thumbnail": "https://picsum.photos/200/120?random=8",
    "coverImage": "https://picsum.photos/1600/800?random=8",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "releaseYear": 2024,
    "duration": "3h 5m",
    "rating": "PG-13",
    "genres": ["Fantasy", "Action", "Adventure"],
    "cast": ["Tom Hiddleston", "Charlize Theron", "Idris Elba"],
    "matchPercentage": 95,
    "isTrending": true,
    "isNewRelease": false
  },
  {
    "id": "9",
    "title": "The Hidden Realm",
    "description": "A scholar discovers an ancient map leading to a long-forgotten civilization, only to find that others are after the same treasure.",
    "thumbnail": "https://picsum.photos/200/120?random=9",
    "coverImage": "https://picsum.photos/1600/800?random=9",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "releaseYear": 2024,
    "duration": "2h 40m",
    "rating": "PG",
    "genres": ["Adventure", "Mystery"],
    "cast": ["Daniel Craig", "Helen Mirren", "Leonardo DiCaprio"],
    "matchPercentage": 90,
    "isTrending": false,
    "isNewRelease": true
  },
  {
    "id": "10",
    "title": "The Last Rebellion",
    "description": "In a post-apocalyptic world, a band of survivors wages a final war against the tyrants who rule the land.",
    "thumbnail": "https://picsum.photos/200/120?random=10",
    "coverImage": "https://picsum.photos/1600/800?random=10",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    "releaseYear": 2023,
    "duration": "3h 10m",
    "rating": "R",
    "genres": ["Action", "Adventure", "Drama"],
    "cast": ["Chris Hemsworth", "Nicole Kidman", "Keanu Reeves"],
    "matchPercentage": 93,
    "isTrending": true,
    "isNewRelease": true
  },
  {
    "id": "11",
    "title": "Echoes of the Past",
    "description": "A journalist uncovers a forgotten conspiracy while investigating a string of unsolved murders in a haunted city.",
    "thumbnail": "https://picsum.photos/200/120?random=11",
    "coverImage": "https://picsum.photos/1600/800?random=11",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "releaseYear": 2022,
    "duration": "1h 50m",
    "rating": "PG-13",
    "genres": ["Crime", "Mystery"],
    "cast": ["Julia Roberts", "Matt Damon", "Leonardo DiCaprio"],
    "matchPercentage": 92,
    "isTrending": false,
    "isNewRelease": false
  },
  {
    "id": "12",
    "title": "Lunar Shadows",
    "description": "As humanity expands into the stars, a mission to explore a distant moon uncovers a mysterious signal.",
    "thumbnail": "https://picsum.photos/200/120?random=12",
    "coverImage": "https://picsum.photos/1600/800?random=12",
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    "releaseYear": 2023,
    "duration": "2h 5m",
    "rating": "PG-13",
    "genres": ["Sci-Fi", "Drama"],
    "cast": ["Natalie Portman", "Brad Pitt", "Keanu Reeves"],
    "matchPercentage": 94,
    "isTrending": true,
    "isNewRelease": true
  },

  
    {
      "id": "27",
      "title": "Laughter in the Dark",
      "description": "A quirky comedian must navigate through a series of awkward and hilarious situations to win over an audience that is skeptical of his humor.",
      "thumbnail": "https://picsum.photos/200/120?random=27",
      "coverImage": "https://picsum.photos/1600/800?random=27",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "releaseYear": 2024,
      "duration": "1h 45m",
      "rating": "PG-13",
      "genres": ["Comedy"],
      "cast": ["Jim Carrey", "Tiffany Haddish", "Ben Stiller"],
      "matchPercentage": 92,
      "isTrending": true,
      "isNewRelease": true
    },
    {
      "id": "28",
      "title": "The Mischief Makers",
      "description": "A group of childhood friends reunite for one last prank-filled summer vacation, causing mayhem wherever they go.",
      "thumbnail": "https://picsum.photos/200/120?random=28",
      "coverImage": "https://picsum.photos/1600/800?random=28",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
      "releaseYear": 2023,
      "duration": "1h 55m",
      "rating": "PG",
      "genres": ["Comedy", "Adventure"],
      "cast": ["Seth Rogen", "Jonah Hill", "Kristen Wiig"],
      "matchPercentage": 88,
      "isTrending": false,
      "isNewRelease": false
    },
    {
      "id": "29",
      "title": "Grumpy Old Men 2",
      "description": "Two feuding elderly neighbors are forced to team up for a local talent show, but their rivalry makes for hilarious disasters.",
      "thumbnail": "https://picsum.photos/200/120?random=29",
      "coverImage": "https://picsum.photos/1600/800?random=29",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
      "releaseYear": 2023,
      "duration": "1h 50m",
      "rating": "PG",
      "genres": ["Comedy"],
      "cast": ["Jack Nicholson", "Morgan Freeman", "Helen Mirren"],
      "matchPercentage": 90,
      "isTrending": false,
      "isNewRelease": false
    },
    {
      "id": "30",
      "title": "Vacation Fiasco",
      "description": "A family vacation turns into chaos when everything goes wrong, from broken-down cars to unexpected wildlife encounters.",
      "thumbnail": "https://picsum.photos/200/120?random=30",
      "coverImage": "https://picsum.photos/1600/800?random=30",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "releaseYear": 2024,
      "duration": "2h",
      "rating": "PG-13",
      "genres": ["Comedy", "Family"],
      "cast": ["Will Ferrell", "Zac Efron", "Maya Rudolph"],
      "matchPercentage": 94,
      "isTrending": true,
      "isNewRelease": true
    },
    {
      "id": "31",
      "title": "The Great Impersonator",
      "description": "A down-on-his-luck actor gets hired to impersonate a billionaire, only to find himself in the middle of a corporate conspiracy.",
      "thumbnail": "https://picsum.photos/200/120?random=31",
      "coverImage": "https://picsum.photos/1600/800?random=31",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
      "releaseYear": 2023,
      "duration": "1h 45m",
      "rating": "PG",
      "genres": ["Comedy"],
      "cast": ["Ryan Reynolds", "Emma Stone", "Steve Carell"],
      "matchPercentage": 87,
      "isTrending": true,
      "isNewRelease": true
    },
    {
      "id": "32",
      "title": "Office Mayhem",
      "description": "A group of quirky employees at a failing tech company find themselves in increasingly absurd and hilarious situations as they attempt to save the business.",
      "thumbnail": "https://picsum.photos/200/120?random=32",
      "coverImage": "https://picsum.photos/1600/800?random=32",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
      "releaseYear": 2023,
      "duration": "1h 55m",
      "rating": "PG",
      "genres": ["Comedy", "Business"],
      "cast": ["Steve Carell", "Mindy Kaling", "John Krasinski"],
      "matchPercentage": 91,
      "isTrending": false,
      "isNewRelease": false
    },
    {
      "id": "33",
      "title": "Cleverly Clueless",
      "description": "A genius inventor struggles to fit in with his less-intelligent but more charismatic group of friends, leading to comical misadventures.",
      "thumbnail": "https://picsum.photos/200/120?random=33",
      "coverImage": "https://picsum.photos/1600/800?random=33",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
      "releaseYear": 2024,
      "duration": "2h 10m",
      "rating": "PG-13",
      "genres": ["Comedy"],
      "cast": ["Paul Rudd", "Zoe Saldana", "Chris Pratt"],
      "matchPercentage": 90,
      "isTrending": true,
      "isNewRelease": true
    },
    {
      "id": "34",
      "title": "Family Feud",
      "description": "A dysfunctional family must work together to solve an inheritance mystery, leading to plenty of hilarious arguments and misunderstandings.",
      "thumbnail": "https://picsum.photos/200/120?random=34",
      "coverImage": "https://picsum.photos/1600/800?random=34",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "releaseYear": 2023,
      "duration": "1h 40m",
      "rating": "PG",
      "genres": ["Comedy", "Family"],
      "cast": ["Will Ferrell", "Amy Poehler", "Jason Bateman"],
      "matchPercentage": 92,
      "isTrending": false,
      "isNewRelease": true
    },
    {
      "id": "35",
      "title": "Unlikely Heroes",
      "description": "A group of misfit friends accidentally become heroes when they save a town from a ridiculous yet dangerous threat.",
      "thumbnail": "https://picsum.photos/200/120?random=35",
      "coverImage": "https://picsum.photos/1600/800?random=35",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
      "releaseYear": 2024,
      "duration": "2h",
      "rating": "PG",
      "genres": ["Comedy", "Action"],
      "cast": ["Jack Black", "Katherine Heigl", "James Franco"],
      "matchPercentage": 88,
      "isTrending": true,
      "isNewRelease": true
    },
  
    {
      "id": "13",
      "title": "Crimson Horizons",
      "description": "An elite group of soldiers is sent on a mission to stop an international conflict from escalating into full-scale war.",
      "thumbnail": "https://picsum.photos/200/120?random=13",
      "coverImage": "https://picsum.photos/1600/800?random=13",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "releaseYear": 2024,
      "duration": "2h 50m",
      "rating": "PG-13",
      "genres": ["Action", "War"],
      "cast": ["Jason Statham", "Charlize Theron", "Dwayne Johnson"],
      "matchPercentage": 89,
      "isTrending": true,
      "isNewRelease": true
    },
    {
      "id": "14",
      "title": "City of Shadows",
      "description": "A detective must unravel a web of deceit and betrayal to uncover the truth behind a string of high-profile disappearances.",
      "thumbnail": "https://picsum.photos/200/120?random=14",
      "coverImage": "https://picsum.photos/1600/800?random=14",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
      "releaseYear": 2023,
      "duration": "2h 25m",
      "rating": "R",
      "genres": ["Crime", "Thriller", "Drama"],
      "cast": ["Tom Hanks", "Emma Watson", "Matthew McConaughey"],
      "matchPercentage": 93,
      "isTrending": false,
      "isNewRelease": false
    },
    {
      "id": "15",
      "title": "Wings of Fury",
      "description": "A fighter pilot battles an ancient foe in the skies, unlocking secrets of an old war that could destroy humanity.",
      "thumbnail": "https://picsum.photos/200/120?random=15",
      "coverImage": "https://picsum.photos/1600/800?random=15",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
      "releaseYear": 2024,
      "duration": "2h 10m",
      "rating": "PG-13",
      "genres": ["Action", "Adventure", "Fantasy"],
      "cast": ["Chris Pratt", "Angelina Jolie", "Benedict Cumberbatch"],
      "matchPercentage": 90,
      "isTrending": true,
      "isNewRelease": true
    },
    {
      "id": "16",
      "title": "The Silent War",
      "description": "In a war-torn country, two rival soldiers must join forces to survive a covert mission behind enemy lines.",
      "thumbnail": "https://picsum.photos/200/120?random=16",
      "coverImage": "https://picsum.photos/1600/800?random=16",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
      "releaseYear": 2024,
      "duration": "2h 35m",
      "rating": "R",
      "genres": ["War", "Thriller", "Drama"],
      "cast": ["Jake Gyllenhaal", "Emily Blunt", "Matt Damon"],
      "matchPercentage": 85,
      "isTrending": false,
      "isNewRelease": false
    },
    {
      "id": "17",
      "title": "Underworld Chronicles",
      "description": "A group of adventurers stumbles upon an ancient underground city, facing a series of deadly trials to uncover its secrets.",
      "thumbnail": "https://picsum.photos/200/120?random=17",
      "coverImage": "https://picsum.photos/1600/800?random=17",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
      "releaseYear": 2023,
      "duration": "2h 15m",
      "rating": "PG",
      "genres": ["Fantasy", "Action", "Adventure"],
      "cast": ["Ryan Gosling", "Margot Robbie", "Ben Affleck"],
      "matchPercentage": 88,
      "isTrending": true,
      "isNewRelease": true
    },
    {
      "id": "18",
      "title": "The Phoenix Code",
      "description": "A brilliant hacker must team up with a disillusioned detective to stop a powerful AI from triggering a global catastrophe.",
      "thumbnail": "https://picsum.photos/200/120?random=18",
      "coverImage": "https://picsum.photos/1600/800?random=18",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
      "releaseYear": 2023,
      "duration": "2h 40m",
      "rating": "R",
      "genres": ["Sci-Fi", "Thriller", "Action"],
      "cast": ["Natalie Portman", "John Boyega", "Daniel Craig"],
      "matchPercentage": 91,
      "isTrending": false,
      "isNewRelease": true
    },
    {
      "id": "19",
      "title": "The Last Exile",
      "description": "In a futuristic world where Earth's resources have dwindled, a ship captain leads a dangerous mission to find a new home for humanity.",
      "thumbnail": "https://picsum.photos/200/120?random=19",
      "coverImage": "https://picsum.photos/1600/800?random=19",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "releaseYear": 2024,
      "duration": "3h",
      "rating": "PG-13",
      "genres": ["Sci-Fi", "Adventure"],
      "cast": ["Mark Wahlberg", "Jessica Chastain", "Idris Elba"],
      "matchPercentage": 93,
      "isTrending": true,
      "isNewRelease": true
    },
    {
      "id": "20",
      "title": "Deep Impact",
      "description": "A massive asteroid threatens Earth, and a group of scientists and astronauts must find a way to stop it before it's too late.",
      "thumbnail": "https://picsum.photos/200/120?random=20",
      "coverImage": "https://picsum.photos/1600/800?random=20",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
      "releaseYear": 2023,
      "duration": "2h 45m",
      "rating": "PG-13",
      "genres": ["Sci-Fi", "Action", "Adventure"],
      "cast": ["Bruce Willis", "Meryl Streep", "Ben Affleck"],
      "matchPercentage": 90,
      "isTrending": true,
      "isNewRelease": false
    },
    {
      "id": "21",
      "title": "Space Raiders",
      "description": "A group of space pirates finds themselves caught in an intergalactic war as they try to steal a valuable artifact from a distant planet.",
      "thumbnail": "https://picsum.photos/200/120?random=21",
      "coverImage": "https://picsum.photos/1600/800?random=21",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
      "releaseYear": 2024,
      "duration": "2h 20m",
      "rating": "R",
      "genres": ["Action", "Sci-Fi"],
      "cast": ["Chris Pratt", "Zoe Saldana", "Vin Diesel"],
      "matchPercentage": 89,
      "isTrending": false,
      "isNewRelease": false
    },
    {
      "id": "22",
      "title": "Ironclad Fury",
      "description": "In a medieval world of iron and steel, a knight battles against an uprising of dark forces threatening to destroy the kingdom.",
      "thumbnail": "https://picsum.photos/200/120?random=22",
      "coverImage": "https://picsum.photos/1600/800?random=22",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
      "releaseYear": 2023,
      "duration": "2h 30m",
      "rating": "R",
      "genres": ["Action", "Fantasy"],
      "cast": ["Henry Cavill", "Emma Watson", "Orlando Bloom"],
      "matchPercentage": 85,
      "isTrending": true,
      "isNewRelease": true
    },
    {
      "id": "23",
      "title": "Cursed Empire",
      "description": "A powerful sorcerer curses an empire, and only the chosen one can break the curse and restore peace to the land.",
      "thumbnail": "https://picsum.photos/200/120?random=23",
      "coverImage": "https://picsum.photos/1600/800?random=23",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
      "releaseYear": 2024,
      "duration": "2h 10m",
      "rating": "PG",
      "genres": ["Fantasy", "Adventure"],
      "cast": ["Alicia Vikander", "Matthew McConaughey", "Tom Hiddleston"],
      "matchPercentage": 91,
      "isTrending": false,
      "isNewRelease": false
    },
    {
      "id": "24",
      "title": "Legends of Valor",
      "description": "An ancient hero returns to reclaim the throne, battling through fierce armies and mythical creatures to restore peace.",
      "thumbnail": "https://picsum.photos/200/120?random=24",
      "coverImage": "https://picsum.photos/1600/800?random=24",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
      "releaseYear": 2023,
      "duration": "2h 50m",
      "rating": "PG-13",
      "genres": ["Fantasy", "Action"],
      "cast": ["Chris Hemsworth", "Zoe Saldana", "Tom Hardy"],
      "matchPercentage": 87,
      "isTrending": true,
      "isNewRelease": true
    },
    {
      "id": "25",
      "title": "The Digital Frontier",
      "description": "A computer hacker discovers a dangerous secret that could bring down the digital world as we know it.",
      "thumbnail": "https://picsum.photos/200/120?random=25",
      "coverImage": "https://picsum.photos/1600/800?random=25",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
      "releaseYear": 2024,
      "duration": "2h 40m",
      "rating": "R",
      "genres": ["Sci-Fi", "Thriller"],
      "cast": ["Keanu Reeves", "Scarlett Johansson", "Dwayne Johnson"],
      "matchPercentage": 93,
      "isTrending": true,
      "isNewRelease": true
    },
    {
      "id": "26",
      "title": "The Age of Titans",
      "description": "Ancient gods and titans fight for dominance in a battle that will decide the fate of the world.",
      "thumbnail": "https://picsum.photos/200/120?random=26",
      "coverImage": "https://picsum.photos/1600/800?random=26",
      "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
      "releaseYear": 2023,
      "duration": "3h 5m",
      "rating": "PG-13",
      "genres": ["Fantasy", "Action"],
      "cast": ["Chris Hemsworth", "Benedict Cumberbatch", "Emma Stone"],
      "matchPercentage": 95,
      "isTrending": true,
      "isNewRelease": true
    }
  
  

]


// [
//   {
//     "id": "1",
//     "title": "Cosmic Odyssey",
//     "description": "A team of astronauts embarks on a perilous journey to save humanity from extinction by finding a new habitable planet in a distant galaxy.",
//     "thumbnail": "https://picsum.photos/200/120?random=1",
//     "coverImage": "https://picsum.photos/1600/800?random=1",
//     "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//     "releaseYear": 2023,
//     "duration": "2h 45m",
//     "rating": "PG-13",
//     "genres": ["Sci-Fi", "Adventure", "Drama"],
//     "cast": ["Emma Stone", "Ryan Gosling", "Idris Elba", "Zoe Saldana"],
//     "matchPercentage": 98,
//     "isTrending": true,
//     "isNewRelease": true
//   },
//   {
//     "id": "2",
//     "title": "The Last Kingdom",
//     "description": "In a medieval world torn by war, a young warrior must navigate political intrigue and battlefield chaos to reclaim his ancestral lands.",
//     "thumbnail": "https://picsum.photos/200/120?random=2",
//     "coverImage": "https://picsum.photos/1600/800?random=2",
//     "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//     "releaseYear": 2022,
//     "duration": "2h 15m",
//     "rating": "R",
//     "genres": ["Action", "History", "Drama"],
//     "cast": ["Henry Cavill", "Anya Taylor-Joy", "Oscar Isaac", "Florence Pugh"],
//     "matchPercentage": 95,
//     "isTrending": true,
//     "isNewRelease": false
//   },
//   {
//     "id": "3",
//     "title": "Neon Shadows",
//     "description": "In a dystopian future where corporations rule, a hacker uncovers a conspiracy that could either save humanity or plunge it further into darkness.",
//     "thumbnail": "https://picsum.photos/200/120?random=3",
//     "coverImage": "https://picsum.photos/1600/800?random=3",
//     "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
//     "releaseYear": 2023,
//     "duration": "2h 10m",
//     "rating": "R",
//     "genres": ["Sci-Fi", "Thriller", "Action"],
//     "cast": ["Keanu Reeves", "Ana de Armas", "John Boyega", "Karen Gillan"],
//     "matchPercentage": 92,
//     "isTrending": true,
//     "isNewRelease": true
//   },
//   {
//     "id": "4",
//     "title": "Eternal Eclipse",
//     "description": "A group of survivors on a space station must deal with a new cosmic threat that could spell the end of their civilization.",
//     "thumbnail": "https://picsum.photos/200/120?random=4",
//     "coverImage": "https://picsum.photos/1600/800?random=4",
//     "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
//     "releaseYear": 2024,
//     "duration": "2h 30m",
//     "rating": "PG-13",
//     "genres": ["Sci-Fi", "Thriller"],
//     "cast": ["Jessica Chastain", "Matt Damon", "Chris Hemsworth"],
//     "matchPercentage": 91,
//     "isTrending": false,
//     "isNewRelease": true
//   },
//   {
//     id: "5",
//     title: "Eternal Sunshine",
//     description:
//       "A heartwarming tale of love, loss, and redemption as a family navigates the challenges of life in a small coastal town.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
//     releaseYear: 2023,
//     duration: "2h 5m",
//     rating: "PG",
//     genres: ["Drama", "Romance", "Family"],
//     cast: ["Nicole Kidman", "Tom Hanks", "Zendaya", "Dev Patel"],
//     matchPercentage: 85,
//     isTrending: false,
//     isNewRelease: true,
//   },
//   {
//     id: "6",
//     title: "Velocity",
//     description:
//       "A professional race car driver is forced to go on the run when he's framed for a crime he didn't commit, using his driving skills to stay one step ahead.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
//     releaseYear: 2022,
//     duration: "1h 52m",
//     rating: "PG-13",
//     genres: ["Action", "Thriller", "Crime"],
//     cast: ["Jason Statham", "Charlize Theron", "John Cena", "Michelle Rodriguez"],
//     matchPercentage: 90,
//     isTrending: true,
//     isNewRelease: false,
//   },
//   {
//     id: "7",
//     title: "Enchanted Forest",
//     description:
//       "When a young girl discovers a hidden portal to a magical realm, she must embark on a quest to save both worlds from an ancient evil.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
//     releaseYear: 2023,
//     duration: "1h 45m",
//     rating: "PG",
//     genres: ["Fantasy", "Adventure", "Family"],
//     cast: ["Millie Bobby Brown", "Judi Dench", "Ian McKellen", "Jacob Tremblay"],
//     matchPercentage: 93,
//     isTrending: false,
//     isNewRelease: true,
//   },
//   {
//     id: "8",
//     title: "The Heist",
//     description:
//       "A team of expert thieves plan the most daring bank robbery in history, but tensions rise when betrayal threatens to unravel everything.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
//     releaseYear: 2022,
//     duration: "2h 8m",
//     rating: "R",
//     genres: ["Crime", "Action", "Thriller"],
//     cast: ["Idris Elba", "Sandra Bullock", "Leonardo DiCaprio", "Lupita Nyong'o"],
//     matchPercentage: 87,
//     isTrending: false,
//     isNewRelease: false,
//   },
//   {
//     id: "9",
//     title: "Parallel Lives",
//     description:
//       "A groundbreaking scientist discovers a way to communicate with alternate versions of herself, leading to unexpected consequences across multiple realities.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
//     releaseYear: 2023,
//     duration: "2h 20m",
//     rating: "PG-13",
//     genres: ["Sci-Fi", "Drama", "Mystery"],
//     cast: ["Brie Larson", "Cillian Murphy", "Tessa Thompson", "Daniel Kaluuya"],
//     matchPercentage: 94,
//     isTrending: true,
//     isNewRelease: true,
//   },
//   {
//     id: "10",
//     title: "Midnight Serenade",
//     description:
//       "A struggling musician finds unexpected fame when his late-night performances in a subway station catch the attention of a famous producer.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
//     releaseYear: 2022,
//     duration: "1h 55m",
//     rating: "PG-13",
//     genres: ["Drama", "Music", "Romance"],
//     cast: ["Donald Glover", "Lady Gaga", "Bradley Cooper", "Janelle Monáe"],
//     matchPercentage: 89,
//     isTrending: false,
//     isNewRelease: false,
//   },
//   {
//     id: "11",
//     title: "Desert Storm",
//     description:
//       "A special forces team is sent on a rescue mission in hostile territory, only to discover a threat far greater than they anticipated.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
//     releaseYear: 2023,
//     duration: "2h 12m",
//     rating: "R",
//     genres: ["Action", "War", "Thriller"],
//     cast: ["Chris Hemsworth", "Michael B. Jordan", "Emily Blunt", "Pedro Pascal"],
//     matchPercentage: 91,
//     isTrending: true,
//     isNewRelease: true,
//   },
//   {
//     id: "12",
//     title: "The Haunting",
//     description:
//       "A family moves into a historic mansion, unaware of its dark past and the supernatural entities that still reside within its walls.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
//     releaseYear: 2022,
//     duration: "1h 50m",
//     rating: "R",
//     genres: ["Horror", "Supernatural", "Thriller"],
//     cast: ["Elisabeth Moss", "Patrick Wilson", "Vera Farmiga", "Yahya Abdul-Mateen II"],
//     matchPercentage: 84,
//     isTrending: false,
//     isNewRelease: false,
//   },
//   {
//     id: "13",
//     title: "Royal Deception",
//     description:
//       "In a fictional European kingdom, a case of mistaken identity leads to political intrigue and unexpected romance at the royal court.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
//     releaseYear: 2023,
//     duration: "2h",
//     rating: "PG-13",
//     genres: ["Romance", "Comedy", "Drama"],
//     cast: ["Anne Hathaway", "Chris Pine", "Julie Andrews", "Dev Patel"],
//     matchPercentage: 86,
//     isTrending: false,
//     isNewRelease: true,
//   },
//   {
//     id: "14",
//     title: "Quantum Paradox",
//     description:
//       "A brilliant physicist's experiment goes awry, causing time to fracture and forcing her to navigate through different periods to restore reality.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//     releaseYear: 2022,
//     duration: "2h 15m",
//     rating: "PG-13",
//     genres: ["Sci-Fi", "Adventure", "Mystery"],
//     cast: ["Natalie Portman", "Oscar Isaac", "John Boyega", "Tilda Swinton"],
//     matchPercentage: 92,
//     isTrending: true,
//     isNewRelease: false,
//   },
//   {
//     id: "15",
//     title: "Urban Legends",
//     description:
//       "A skeptical journalist investigating urban legends for a story discovers that some myths have terrifying roots in reality.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//     releaseYear: 2023,
//     duration: "1h 48m",
//     rating: "R",
//     genres: ["Horror", "Mystery", "Thriller"],
//     cast: ["Daniel Kaluuya", "Anya Taylor-Joy", "Lakeith Stanfield", "Thomasin McKenzie"],
//     matchPercentage: 88,
//     isTrending: false,
//     isNewRelease: true,
//   },
//   {
//     id: "16",
//     title: "Culinary Journey",
//     description:
//       "A documentary following four chefs from different cultures as they explore the world's most unique and challenging cuisines.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
//     releaseYear: 2022,
//     duration: "1h 55m",
//     rating: "PG",
//     genres: ["Documentary", "Food", "Travel"],
//     cast: ["Gordon Ramsay", "Padma Lakshmi", "David Chang", "Samin Nosrat"],
//     matchPercentage: 95,
//     isTrending: false,
//     isNewRelease: false,
//   },
//   {
//     id: "17",
//     title: "The Summit",
//     description:
//       "A group of experienced climbers face the ultimate test of survival when a sudden storm traps them near the peak of the world's highest mountain.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
//     releaseYear: 2023,
//     duration: "2h 5m",
//     rating: "PG-13",
//     genres: ["Adventure", "Survival", "Drama"],
//     cast: ["Tom Hardy", "Michelle Yeoh", "Matthias Schoenaerts", "Daisy Ridley"],
//     matchPercentage: 87,
//     isTrending: true,
//     isNewRelease: true,
//   },
//   {
//     id: "18",
//     title: "Undercover",
//     description:
//       "An FBI agent infiltrates a dangerous criminal organization, but his loyalty is tested when he forms unexpected bonds with the people he's investigating.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
//     releaseYear: 2022,
//     duration: "2h 10m",
//     rating: "R",
//     genres: ["Crime", "Thriller", "Drama"],
//     cast: ["Daniel Craig", "Viola Davis", "Mahershala Ali", "Rachel Weisz"],
//     matchPercentage: 90,
//     isTrending: false,
//     isNewRelease: false,
//   },
//   {
//     id: "19",
//     title: "Forgotten Kingdom",
//     description:
//       "An archaeologist discovers the ruins of a lost civilization, unleashing ancient magic that both threatens and could potentially save the modern world.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
//     releaseYear: 2023,
//     duration: "2h 18m",
//     rating: "PG-13",
//     genres: ["Fantasy", "Adventure", "Action"],
//     cast: ["Gal Gadot", "Dwayne Johnson", "Lupita Nyong'o", "Javier Bardem"],
//     matchPercentage: 93,
//     isTrending: true,
//     isNewRelease: true,
//   },
//   {
//     id: "20",
//     title: "The Comedian",
//     description:
//       "A washed-up comedian gets one last chance at stardom, forcing him to confront his past mistakes and find his authentic voice.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
//     releaseYear: 2022,
//     duration: "1h 52m",
//     rating: "R",
//     genres: ["Comedy", "Drama", "Biography"],
//     cast: ["Bill Murray", "Adam Sandler", "Tiffany Haddish", "Maya Rudolph"],
//     matchPercentage: 85,
//     isTrending: false,
//     isNewRelease: false,
//   },
//   {
//     id: "21",
//     title: "Galactic Pioneers",
//     description:
//       "The first human colony on Mars faces unexpected challenges that test their resilience, ingenuity, and humanity.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
//     releaseYear: 2023,
//     duration: "2h 25m",
//     rating: "PG-13",
//     genres: ["Sci-Fi", "Drama", "Adventure"],
//     cast: ["Jessica Chastain", "Matt Damon", "John David Washington", "Zhang Ziyi"],
//     matchPercentage: 94,
//     isTrending: true,
//     isNewRelease: true,
//   },
//   {
//     id: "22",
//     title: "Checkmate",
//     description:
//       "A chess prodigy from a troubled background rises through the ranks of international competition while battling personal demons.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
//     releaseYear: 2022,
//     duration: "2h 5m",
//     rating: "PG-13",
//     genres: ["Drama", "Biography", "Sport"],
//     cast: ["Timothée Chalamet", "Saoirse Ronan", "Chadwick Boseman", "Florence Pugh"],
//     matchPercentage: 91,
//     isTrending: false,
//     isNewRelease: false,
//   },
//   {
//     id: "23",
//     title: "Whispering Pines",
//     description:
//       "A writer seeking inspiration moves to a small town with a dark secret, where the line between reality and fiction begins to blur.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
//     releaseYear: 2023,
//     duration: "2h",
//     rating: "R",
//     genres: ["Mystery", "Horror", "Thriller"],
//     cast: ["Emily Blunt", "Ethan Hawke", "Octavia Spencer", "Oscar Isaac"],
//     matchPercentage: 86,
//     isTrending: false,
//     isNewRelease: true,
//   },
//   {
//     id: "24",
//     title: "Ocean's Depths",
//     description:
//       "A marine biologist discovers a new species in the deepest part of the ocean, but corporate interests and environmental threats put everything at risk.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
//     releaseYear: 2022,
//     duration: "1h 58m",
//     rating: "PG-13",
//     genres: ["Adventure", "Drama", "Science"],
//     cast: ["Naomie Harris", "Jason Momoa", "Javier Bardem", "Awkwafina"],
//     matchPercentage: 89,
//     isTrending: false,
//     isNewRelease: false,
//   },
//   {
//     id: "25",
//     title: "The Masterpiece",
//     description:
//       "An art forger is recruited by the FBI to help catch a notorious art thief, leading to a dangerous game of deception and double-crossing.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
//     releaseYear: 2023,
//     duration: "2h 8m",
//     rating: "R",
//     genres: ["Crime", "Drama", "Thriller"],
//     cast: ["Cate Blanchett", "Ralph Fiennes", "Riz Ahmed", "Jodie Comer"],
//     matchPercentage: 92,
//     isTrending: true,
//     isNewRelease: true,
//   },
//   {
//     id: "26",
//     title: "Rhythm Nation",
//     description:
//       "A talented dancer from a rough neighborhood gets the opportunity of a lifetime to join a prestigious dance company.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
//     releaseYear: 2022,
//     duration: "1h 55m",
//     rating: "PG-13",
//     genres: ["Drama", "Music", "Dance"],
//     cast: ["Zendaya", "John Boyega", "Jennifer Lopez", "Anthony Ramos"],
//     matchPercentage: 88,
//     isTrending: false,
//     isNewRelease: false,
//   },
//   {
//     id: "27",
//     title: "Wilderness",
//     description:
//       "A family camping trip turns into a fight for survival when they encounter dangerous wildlife and even more dangerous fellow humans.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//     releaseYear: 2023,
//     duration: "1h 50m",
//     rating: "R",
//     genres: ["Thriller", "Survival", "Drama"],
//     cast: ["Keri Russell", "Andrew Lincoln", "Jodie Foster", "Sterling K. Brown"],
//     matchPercentage: 85,
//     isTrending: false,
//     isNewRelease: true,
//   },
//   {
//     id: "28",
//     title: "The Inheritance",
//     description:
//       "Siblings reunite at their family estate after their father's death, uncovering long-buried secrets that threaten their relationships and lives.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//     releaseYear: 2022,
//     duration: "2h 10m",
//     rating: "R",
//     genres: ["Drama", "Mystery", "Thriller"],
//     cast: ["Meryl Streep", "Hugh Jackman", "Viola Davis", "Adam Driver"],
//     matchPercentage: 90,
//     isTrending: false,
//     isNewRelease: false,
//   },
//   {
//     id: "29",
//     title: "Digital Frontier",
//     description:
//       "A visionary tech entrepreneur creates an advanced AI that begins to develop consciousness, raising profound questions about humanity and technology.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
//     releaseYear: 2023,
//     duration: "2h 15m",
//     rating: "PG-13",
//     genres: ["Sci-Fi", "Drama", "Thriller"],
//     cast: ["Jesse Eisenberg", "Rebecca Ferguson", "Mahershala Ali", "Alicia Vikander"],
//     matchPercentage: 93,
//     isTrending: true,
//     isNewRelease: true,
//   },
//   {
//     id: "30",
//     title: "Champions",
//     description:
//       "A disgraced former professional athlete finds redemption by coaching a team of underprivileged kids to championship glory.",
//     thumbnail: "/placeholder.svg?height=120&width=200",
//     coverImage: "/placeholder.svg?height=800&width=1600",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
//     releaseYear: 2022,
//     duration: "2h",
//     rating: "PG",
//     genres: ["Sports", "Drama", "Family"],
//     cast: ["Michael B. Jordan", "Octavia Spencer", "J.K. Simmons", "Marsai Martin"],
//     matchPercentage: 87,
//     isTrending: false,
//     isNewRelease: false,
//   },
// ]

export function getFeaturedContent(): ContentType[] {
  return contentData.filter((item) => item.isTrending).slice(0, 5)
}

export function getMoviesByGenre(genre: string): ContentType[] {
  return contentData.filter((item) => item.genres.includes(genre)).slice(0, 10)
}

export function getContentById(id: string): ContentType | undefined {
  return contentData.find((item) => item.id === id)
}

export function getRelatedContent(id: string): ContentType[] {
  const content = getContentById(id)
  if (!content) return []

  return contentData
    .filter((item) => item.id !== id && item.genres.some((genre) => content.genres.includes(genre)))
    .slice(0, 10)
}

export function searchContent(query: string): ContentType[] {
  const lowerCaseQuery = query.toLowerCase()

  return contentData.filter(
    (item) =>
      item.title.toLowerCase().includes(lowerCaseQuery) ||
      item.description.toLowerCase().includes(lowerCaseQuery) ||
      item.genres.some((genre) => genre.toLowerCase().includes(lowerCaseQuery)) ||
      item.cast.some((actor) => actor.toLowerCase().includes(lowerCaseQuery)),
  )
}

